const mongoose = require('mongoose');

const analyticsSchema = new mongoose.Schema({
  // Analytics Type
  type: {
    type: String,
    required: true,
    enum: [
      'user_activity',
      'blood_request_trends',
      'donation_statistics',
      'geographic_distribution',
      'response_times',
      'success_rates',
      'user_engagement',
      'system_performance',
      'predictive_analysis',
      'compliance_metrics'
    ]
  },
  
  // Time Period
  period: {
    type: String,
    required: true,
    enum: ['hourly', 'daily', 'weekly', 'monthly', 'yearly']
  },
  startDate: {
    type: Date,
    required: true
  },
  endDate: {
    type: Date,
    required: true
  },
  
  // Data Points
  data: {
    type: mongoose.Schema.Types.Mixed,
    required: true
  },
  
  // Metrics
  metrics: {
    totalUsers: { type: Number, default: 0 },
    activeUsers: { type: Number, default: 0 },
    newUsers: { type: Number, default: 0 },
    totalRequests: { type: Number, default: 0 },
    completedRequests: { type: Number, default: 0 },
    totalDonations: { type: Number, default: 0 },
    successfulDonations: { type: Number, default: 0 },
    averageResponseTime: { type: Number, default: 0 },
    successRate: { type: Number, default: 0 },
    engagementRate: { type: Number, default: 0 }
  },
  
  // Geographic Data
  geographicData: [{
    location: {
      country: String,
      state: String,
      city: String,
      coordinates: {
        type: {
          type: String,
          enum: ['Point'],
          default: 'Point'
        },
        coordinates: [Number]
      }
    },
    count: Number,
    percentage: Number
  }],
  
  // Blood Type Distribution
  bloodTypeDistribution: [{
    bloodType: {
      type: String,
      enum: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']
    },
    count: Number,
    percentage: Number
  }],
  
  // Age Group Distribution
  ageGroupDistribution: [{
    ageGroup: String, // e.g., '18-25', '26-35', etc.
    count: Number,
    percentage: Number
  }],
  
  // Gender Distribution
  genderDistribution: [{
    gender: {
      type: String,
      enum: ['male', 'female', 'other']
    },
    count: Number,
    percentage: Number
  }],
  
  // Predictive Insights
  predictions: {
    nextWeekDemand: Number,
    nextMonthDemand: Number,
    seasonalTrends: [{
      month: String,
      predictedDemand: Number,
      confidence: Number
    }],
    riskFactors: [{
      factor: String,
      impact: Number,
      probability: Number
    }]
  },
  
  // Performance Metrics
  performance: {
    averageLoadTime: Number,
    errorRate: Number,
    uptime: Number,
    throughput: Number,
    responseTime: Number
  },
  
  // Generated By
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  generatedAt: {
    type: Date,
    default: Date.now
  },
  
  // Status
  status: {
    type: String,
    enum: ['processing', 'completed', 'failed'],
    default: 'completed'
  },
  
  // Additional Metadata
  metadata: {
    type: mongoose.Schema.Types.Mixed,
    default: {}
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes
analyticsSchema.index({ type: 1, startDate: 1, endDate: 1 });
analyticsSchema.index({ period: 1, createdAt: -1 });
analyticsSchema.index({ generatedAt: -1 });

// Virtual for duration
analyticsSchema.virtual('duration').get(function() {
  return Math.ceil((this.endDate - this.startDate) / (1000 * 60 * 60 * 24));
});

// Static method to generate user activity analytics
analyticsSchema.statics.generateUserActivity = async function(startDate, endDate) {
  const User = mongoose.model('User');
  const BloodRequest = mongoose.model('BloodRequest');
  const Donation = mongoose.model('Donation');
  
  const [
    totalUsers,
    activeUsers,
    newUsers,
    totalRequests,
    completedRequests,
    totalDonations,
    successfulDonations
  ] = await Promise.all([
    User.countDocuments({ createdAt: { $lte: endDate } }),
    User.countDocuments({ 
      lastActivity: { $gte: startDate, $lte: endDate },
      isActive: true 
    }),
    User.countDocuments({ createdAt: { $gte: startDate, $lte: endDate } }),
    BloodRequest.countDocuments({ createdAt: { $gte: startDate, $lte: endDate } }),
    BloodRequest.countDocuments({ 
      createdAt: { $gte: startDate, $lte: endDate },
      status: 'completed'
    }),
    Donation.countDocuments({ createdAt: { $gte: startDate, $lte: endDate } }),
    Donation.countDocuments({ 
      createdAt: { $gte: startDate, $lte: endDate },
      status: 'distributed'
    })
  ]);
  
  const successRate = totalRequests > 0 ? (completedRequests / totalRequests) * 100 : 0;
  
  return new this({
    type: 'user_activity',
    period: 'daily',
    startDate,
    endDate,
    data: {
      totalUsers,
      activeUsers,
      newUsers,
      totalRequests,
      completedRequests,
      totalDonations,
      successfulDonations
    },
    metrics: {
      totalUsers,
      activeUsers,
      newUsers,
      totalRequests,
      completedRequests,
      totalDonations,
      successfulDonations,
      successRate
    }
  });
};

// Static method to generate blood request trends
analyticsSchema.statics.generateBloodRequestTrends = async function(startDate, endDate) {
  const BloodRequest = mongoose.model('BloodRequest');
  
  const trends = await BloodRequest.aggregate([
    {
      $match: {
        createdAt: { $gte: startDate, $lte: endDate }
      }
    },
    {
      $group: {
        _id: {
          bloodType: '$bloodType',
          urgency: '$urgency',
          status: '$status'
        },
        count: { $sum: 1 }
      }
    },
    {
      $group: {
        _id: '$_id.bloodType',
        total: { $sum: '$count' },
        byUrgency: {
          $push: {
            urgency: '$_id.urgency',
            status: '$_id.status',
            count: '$count'
          }
        }
      }
    }
  ]);
  
  return new this({
    type: 'blood_request_trends',
    period: 'daily',
    startDate,
    endDate,
    data: { trends },
    bloodTypeDistribution: trends.map(trend => ({
      bloodType: trend._id,
      count: trend.total,
      percentage: 0 // Will be calculated
    }))
  });
};

// Static method to generate geographic distribution
analyticsSchema.statics.generateGeographicDistribution = async function(startDate, endDate) {
  const User = mongoose.model('User');
  const BloodRequest = mongoose.model('BloodRequest');
  
  const [userDistribution, requestDistribution] = await Promise.all([
    User.aggregate([
      {
        $match: {
          createdAt: { $gte: startDate, $lte: endDate }
        }
      },
      {
        $group: {
          _id: {
            city: '$address.city',
            state: '$address.state',
            country: '$address.country'
          },
          count: { $sum: 1 }
        }
      },
      {
        $sort: { count: -1 }
      }
    ]),
    BloodRequest.aggregate([
      {
        $match: {
          createdAt: { $gte: startDate, $lte: endDate }
        }
      },
      {
        $group: {
          _id: {
            city: '$city',
            state: '$state'
          },
          count: { $sum: 1 }
        }
      },
      {
        $sort: { count: -1 }
      }
    ])
  ]);
  
  return new this({
    type: 'geographic_distribution',
    period: 'daily',
    startDate,
    endDate,
    data: {
      userDistribution,
      requestDistribution
    },
    geographicData: userDistribution.map(item => ({
      location: {
        city: item._id.city,
        state: item._id.state,
        country: item._id.country
      },
      count: item.count,
      percentage: 0 // Will be calculated
    }))
  });
};

// Static method to generate predictive analysis
analyticsSchema.statics.generatePredictiveAnalysis = async function() {
  const BloodRequest = mongoose.model('BloodRequest');
  
  // Get historical data for the last 6 months
  const sixMonthsAgo = new Date();
  sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);
  
  const historicalData = await BloodRequest.aggregate([
    {
      $match: {
        createdAt: { $gte: sixMonthsAgo }
      }
    },
    {
      $group: {
        _id: {
          year: { $year: '$createdAt' },
          month: { $month: '$createdAt' },
          bloodType: '$bloodType'
        },
        count: { $sum: 1 }
      }
    },
    {
      $sort: { '_id.year': 1, '_id.month': 1 }
    }
  ]);
  
  // Simple linear regression for prediction
  const predictions = this.calculatePredictions(historicalData);
  
  return new this({
    type: 'predictive_analysis',
    period: 'monthly',
    startDate: new Date(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // Next month
    data: {
      historicalData,
      predictions
    },
    predictions: {
      nextWeekDemand: predictions.nextWeek,
      nextMonthDemand: predictions.nextMonth,
      seasonalTrends: predictions.seasonal,
      riskFactors: predictions.risks
    }
  });
};

// Helper method to calculate predictions
analyticsSchema.statics.calculatePredictions = function(historicalData) {
  // Simple prediction logic - in a real system, you'd use more sophisticated ML models
  const totalRequests = historicalData.reduce((sum, item) => sum + item.count, 0);
  const averageMonthly = totalRequests / 6;
  
  return {
    nextWeek: Math.round(averageMonthly / 4),
    nextMonth: Math.round(averageMonthly),
    seasonal: [
      { month: 'Jan', predictedDemand: Math.round(averageMonthly * 1.1), confidence: 0.8 },
      { month: 'Feb', predictedDemand: Math.round(averageMonthly * 0.9), confidence: 0.8 },
      { month: 'Mar', predictedDemand: Math.round(averageMonthly * 1.0), confidence: 0.8 }
    ],
    risks: [
      { factor: 'Seasonal flu', impact: 0.3, probability: 0.7 },
      { factor: 'Holiday season', impact: 0.2, probability: 0.8 }
    ]
  };
};

// Static method to get analytics summary
analyticsSchema.statics.getAnalyticsSummary = async function(period = 'daily', limit = 30) {
  const endDate = new Date();
  const startDate = new Date();
  
  switch (period) {
    case 'hourly':
      startDate.setHours(endDate.getHours() - limit);
      break;
    case 'daily':
      startDate.setDate(endDate.getDate() - limit);
      break;
    case 'weekly':
      startDate.setDate(endDate.getDate() - (limit * 7));
      break;
    case 'monthly':
      startDate.setMonth(endDate.getMonth() - limit);
      break;
  }
  
  return await this.find({
    period,
    startDate: { $gte: startDate },
    endDate: { $lte: endDate }
  })
  .sort({ startDate: -1 })
  .limit(limit);
};

module.exports = mongoose.model('Analytics', analyticsSchema);
